name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Touch .isaac_ros_common-config
      run: |
        touch workspace/src/isaac_ros_common/scripts/.isaac_ros_common-config
    - name: Build the Docker image
      run: |
        PLATFORM=aarch64 CONFIG_DOCKER_SEARCH_DIRS=../../../../ ./workspace/src/isaac_ros_common/scripts/build_base_image.sh aarch64.ros2_humble.zed.user.rover rover_isaac_ros-aarch64 '' '' ''
    - name: Tag & push the image
      run: |
        DATESTAMP=$(date +%s)
        docker tag rover_isaac_ros-aarch64:latest ${{ secrets.DOCKERHUB_USERNAME }}/rover_isaac_ros-aarch64:${DATESTAMP}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rover_isaac_ros-aarch64:${DATESTAMP}
